site_name: '${{values.app_name}}'
site_description: 'Main documentation for the ${{values.app_name}}'
repo_url: https://github.com/ricardoandre97/${{values.app_name}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'